### PR TITLE
Medical: language refactor

### PR DESCRIPTION
**Pull request by dastrukar**
Not sure if this is best way to handle the new LANGUAGE changes, but it should at least remove some redundant parts and tidy up some of the code.

note: still questioning on how to handle wound descriptions, and let me know if there's a cleaner way to implement the language stuff

### CODE REVIEW

**Comment by dastrukar** [comment]
With https://github.com/caligari87/Ugly-as-Sin/pull/219/commits/5c53e7900658962a57f14864af82d870deaaf356, the trauma kit no longer uses LANGUAGE (or just hard-coded strings) to display the blocking item name. (excluding bandages and `striptime`)
So instead of displaying `Take off your armour first!`, it would say `Take off your garrison armour first!` (or whatever armour you have)
@caligari87 let me know if you'd prefer the original behaviour

**Comment by dastrukar** [comment]
@tedthedragon btw, what's the rationale behind moving all of the colour codes to LANGUAGE?
e.g. `UAS_MEDICAL_UI_BLACK` / `UI_STATUS_BLACK`

**Comment by caligari87** [comment]
The dynamic tag usage is definitely preferred. I never really iterated on that part of the module past basic functionality anyway. 

I like these changes, they make the code more readable for sure.

**Comment by dastrukar** [comment]
Thanks for the feedback :]

Anyways, assuming that ted's probably not going to respond, I'll just leave the colour stuff alone and mark this PR as ready to merge.

**Comment by tedthedragon** [comment]
> @tedthedragon btw, what's the rationale behind moving all of the colour codes to LANGUAGE? e.g. `UAS_MEDICAL_UI_BLACK` / `UI_STATUS_BLACK`

My bad, I didn't get the notification that I was mentioned in this

The intention was, as I'm slightly colorblind, that I could modify the colors to have it be more visible for me to read for some of the wound changes and, if someone prefers a different UI color, they could also change it to their preferences.

**Comment by dastrukar** [comment]
Noted. Will keep that in mind if I end up messing with the LANGUAGE file in the future.

**Pull request merged**
