### PR TITLE
Localize a large chunk of the medical strings.

### PR DESCRIPTION
**Pull request by tedthedragon**
This should cover most of the new medical module strings to be translatable, stuff that's known missing (mostly because I can't be assed to change constants into something translatable right now) are the following:

- Line 202 to 215 in medical_wound.zsc
- Line 100 to 135 in traumakit_forceps.zsc
- Line 274 and 275 in traumakit_hud.zsc
- Line 48 to 114 in traumakit_pain.zsc

All of these can likely be completed with a very similar solution, I just haven't tried to figure out that solution nor do I really have the time and mental capacity to do that just yet due to irl issues.

### CODE REVIEW

**Comment by tedthedragon** [comment]
As mentioned by Zeratul like right after I made this PR, may be able to localize the const's in a similar way to how helptext is done, not sure for certain though.

**Comment by tedthedragon** [comment]
I'm not seeing any rebase conflicts and github's telling me outright that there's none. Not sure what I can do nor what you really want.

**Comment by dastrukar** [comment]
Took a look through all the changes. IMO, I think the code for the description stuff needs a refactor in order to make the LANGUAGE stuff work better, since parts like these:
```
UAS_BANDAGING_HELPTEXT_NOBLOODBAGATTACHED = "There's no blood bag attached to ";
UAS_BANDAGING_HELPTEXT_YOU = "you.";
UAS_BANDAGING_HELPTEXT_THEM = "them.";
```
just makes it more annoying to maintain and is less flexible.
Could probably be more like this:
```
UAS_BANDAGING_HELPTEXT_NOBLOODBAG_YOU = "There's no blood bag attached to you.";
UAS_BANDAGING_HELPTEXT_NOBLOODBAG_THEM = "There's no blood bag attached to them.";
```
Of course, the code needs to change in order to adapt to this... If this does get merged as is, I wouldn't mind doing the refactor.


> I'm hesitant to do a squash/merge since this is a somewhat WIP module at the moment and I don't know if it's going to overwrite something recent.

On that note, this might make development more tedious, but oh well, such is the pain of maintaining language lumps.

**Comment by tedthedragon** [comment]
I'll upkeep whatever's not translated whenever needed also, I'll probably do the bloodbag suggestion though the original intention of this entire PR is just to get whatever localization can be done without changing code in ways that'd be drastic, hence why any of the pain string constants I haven't touched et cetera.

There's a lot of things that can be done more efficiently, though those can be done in the future

**Pull request merged**
